### PR TITLE
FIX #142 Responsive width large screens

### LINKED ISSUE #142: Responsive width large screens
# Responsive width

On wide screens, the content doesn't scale responsively. It makes it harder to decipher plots.
image

### PR DESCRIPTION
**Pull request by ezioishan**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [✔️ ] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs
#142 

## What does this implement/fix? Explain your changes.

This PR fixes the lack of responsiveness in wider screens. When looking at the page with dev tools, found that the container for the body and the appbar has an in-built (default Material-UI) styling as:

Screenshot (116)

To overwrite the above styling, wrote a style as 'containerStyle':
Screenshot (115)

### CODE REVIEW

**Comment by c-bata** [comment]
Hi @ezioishan. Thank you for your pull request. Could you fix a CI failure?

**Comment by ezioishan** [comment]
Hey, can you explain me about this CI failure. I don't have any idea about it. I'll try to fix it then.

**Comment by c-bata** [comment]
I guess you need to run prettier, a code formatter for TypeScript. Please run `npm run fmt` to pass `npm run lint`.

**Comment by ezioishan** [comment]
Okay, I will do it right away! Thanks.

**Comment by ezioishan** [comment]
Is this good enough to merge or are there any changes to be made? Please let me know I'll make the changes accordingly.

**Review by c-bata — APPROVED** [review]
LGTM! Thank you for your contribution.

**Pull request merged**
