### PR TITLE
Unify duplicated logic in plotSlice

### PR DESCRIPTION
**Pull request by knshnb**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## What does this implement/fix? Explain your changes.
A small refactoring of `plotSlice`, which does not change the behavior of the code.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
Sorry, I missed the assignees. Fixed.

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
