### PR TITLE
Add support for Optuna's study artifacts

### PR DESCRIPTION
**Pull request by c-bata**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

Refs https://github.com/optuna/optuna/pull/4905

## What does this implement/fix? Explain your changes.

See https://github.com/optuna/optuna/pull/4905 for details.

### CODE REVIEW

**Comment by c-bata** [comment]
@gen740 Could you review this PR?

**Review by gen740 — APPROVED** [review]
LGTM! I've tested it in my local environment and it works as expected.

**Comment by gen740** [comment]
@c-bata Please merge the main branch before merging this PR.

**Comment by c-bata** [comment]
@gen740 Thank you for your review! I've merged the main branch. Let me merge this PR after passing tests.

**Pull request merged**
