### PR TITLE
Replace example files with links.

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

This PR is related to https://github.com/optuna/optuna-examples/pull/224.

## What does this implement/fix? Explain your changes.

This pull request should be merged subsequent to  https://github.com/optuna/optuna-examples/pull/224. The key changes include:

- The examples previously located in this repository have been removed.
- A new `examples/README.md` has been created to direct users to the updated examples in the `optuna/optuna-examples` repository.
- Links in the docs have been updated to reflect these changes.

Please note that these changes will streamline user navigation and maintain the repository's organization.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
Note that we need to fix the link in the tutorial of HITL optimization in Optuna [here](https://optuna-dashboard.readthedocs.io/en/latest/tutorials/hitl.html#environment-setup).

**Comment by not522** [comment]
> A new examples/README.md has been created to direct users to the updated examples in the optuna/optuna-examples repository.

This change is not seen in this PR. I guess that you forgot to add it. Could you check it?

**Comment by toshihikoyanase** [comment]
@not522 Good catch! I added the REAMDE file in https://github.com/optuna/optuna-dashboard/pull/684/commits/985b301f67b54ebff12c400777cf76100c68a63c. PTAL.

**Comment by not522** [comment]
Could you also change the link in `docs/tutorials/preferential-optimization.rst`?

**Comment by toshihikoyanase** [comment]
Thank you for pointing it out. I updated the preferential optimization tutorial in https://github.com/optuna/optuna-dashboard/pull/684/commits/da70fbe2fa0df813f84c2fc03a85a6e3a3f88063.

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
