### PR TITLE
Use WaveSurfer instead of `audio` tag.

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

A possible follow-up for https://github.com/optuna/optuna-dashboard/issues/629.

## What does this implement/fix? Explain your changes.

* Install [WaveSurfer](https://wavesurfer.xyz/) to play audio artifacts.
* Add `WaveSurferArtifactViewer` based on the [official example](https://wavesurfer.xyz/examples/?react.js)
* Use the `WaveSurferArtifactViewer` instead of `audio` tag in the ArtifactCardMedia.tsx

### CODE REVIEW

**Comment by c-bata** [comment]
@contramundum53 Could you review this PR?

**Comment by c-bata** [comment]
@keisuke-umezawa Could you review this PR?

**Comment by contramundum53** [comment]
There seems to be a problem that the audio is stopped when automatic update runs.

**Comment by toshihikoyanase** [comment]
You're right. The `WaveSurferArtifactViewer` gets recreated unexpectedly every time the automatic update runs.
I'll investigate what triggers the recreation. Thanks.

**Comment by toshihikoyanase** [comment]
I found that we did not need to observe the options of wavesurfer, such as URL of the audio file, since the Optuna artifacts including audio files are not designed to be updated in-place. They are usually removed and re-uploaded instead.

I guess we can keep playing the audio now, so please take another look.

**Review by keisuke-umezawa — APPROVED** [review]
@toshihikoyanase 
LGTM! After the purpose of this PR is clear, I will merge it.

**Pull request merged**
