### PR TITLE
Use `plot_param_importances` in backend

### PR DESCRIPTION
**Pull request by knshnb**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@nabenabe0928 Could you review this PR?

**Comment by knshnb** [comment]
@HideakiImamura Sorry to confuse you, but this is just a prototype and not ready for review currently.

**Comment by HideakiImamura** [comment]
Oh, I see. I reset the assignees.

**Comment by c-bata** [comment]
@knshnb Should we close this PR?

**Comment by knshnb** [comment]
Let me close this because I worked on this with other PRs: https://github.com/optuna/optuna-dashboard/pull/764

**Comment by knshnb** [comment]
Let me close this because I worked on this with other PRs: https://github.com/optuna/optuna-dashboard/pull/764

**Pull request closed without merging**
